# .github/workflows/pages.yml
name: Build and Deploy to GitHub Pages

# Se lanza en cada push a la rama main
on:
  push:
    branches:
      - main

# Permisos necesarios para leer el código y escribir en Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1) Clona tu repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # (Opcional) 2) Si tuvieras un build (npm, hugo, etc), lo pondrías aquí.
      # - name: Instalar dependencias y build
      #   run: |
      #     npm ci
      #     npm run build

      # 3) Configura GitHub Pages
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      # 4) Empaqueta los archivos a publicar
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Ruta relativa de tu contenido web. 
          # Si todo está en la raíz (index.html, about.html, etc):
          path: ./

      # 5) Publica en Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

      # 6) (Opcional) Notificar URL
      - name: Show site URL
        run: echo "Your site is live at https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
